### ISSUE TITLE
Extract: cannot read location data from region file "../lib/region/r.-1.-2.mca": EOF

### ISSUE THREAD

**Issue by Arinerron** [bwkimmel/mcstrings#1]
sad

**Comment by bwkimmel** [comment]
Sorry to hear this is not working for you. Could you provide more information about the steps you took to reproduce this?

- What was the exact command(s) that you ran?
- With which version of Minecraft did you create this world?
- With which version of Minecraft did you most recently load this world?
- Could you provide a zip of your Minecraft world for which you are having this problem so that I could try to reproduce your problem? Ideally, create a new Minecraft world and then make the minimum amount of changes in that world that would still allow you to observe this error.

Thanks!

**Comment by Arinerron** [comment]
Hey! We used this project to solve the "library of babel" chal in DamCTF. You can download the world files at https://damctf.xyz/. The event is over now so I can talk about it.

The flag is stored in one of the books so we had to dump strings to find it.

**Comment by bwkimmel** [comment]
Could you be more specific? I cannot find a link to any world download on that page. Here is an archive of what I see there: https://archive.md/xYkav

**Comment by bwkimmel** [comment]
I did look through the instructions doc and the discord group.

**Comment by Arinerron** [comment]
Yup, sorry, I was on mobile. It's this challenge:
![image](https://user-images.githubusercontent.com/3926753/140799017-397b899d-9b08-4f98-b5ab-e74860f1987c.png)
https://damctf-2021-prod-storage.storage.googleapis.com/uploads/2d6a0ed824168a7246d3005f93aaf1cf844059b5413fcb3b559af33e1da5e2ef/library-of-babel.zip

You have to register an account to see a list of challenges. I uploaded it to Google Drive in case you don't have perms to access that link: https://drive.google.com/file/d/1qfLAh4Tz4jA_9JRg92UDqgslCj84UHjg/view?usp=sharing

Flag format is `dam{...}`

**Comment by bwkimmel** [comment]
Thanks! I was able to reproduce your issue. It seems that some of the region files in the world have zero length.

```shell
$ find . -size 0
./library-of-babel/region/r.0.-2.mca
./library-of-babel/region/r.-2.-2.mca
./library-of-babel/region/r.-1.-2.mca
./library-of-babel/entities/r.-1.1.mca
./library-of-babel/entities/r.-2.0.mca
./library-of-babel/entities/r.-1.-1.mca
./library-of-babel/entities/r.0.0.mca
./library-of-babel/entities/r.0.1.mca
./library-of-babel/entities/r.0.-1.mca
./library-of-babel/entities/r.-2.-1.mca
./library-of-babel/poi/r.-2.0.mca
./library-of-babel/poi/r.-1.-1.mca
./library-of-babel/poi/r.0.0.mca
./library-of-babel/poi/r.0.-1.mca
```

From my understanding, this seems to go against the Anvil file format spec, which says that each region file should have an 8kB header: https://minecraft.fandom.com/wiki/Region_file_format#Structure. This tool is expecting that header to be present, so you get an "EOF" error when it tries to read an empty region file.

I can update this tool to skip over empty files. Until then, you can work around the problem by removing empty region files from the world.
